server:
  port: 9102
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters: TokenRelay
      routes:
        - id: route-account-management
          uri: lb://AccountManagementMS
          predicates:
            - Path=/api/account/**
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak-sso:
            issuer-uri: http://141.95.103.210:8090/auth/realms/changeRealm
        registration:
          GatewayMs:
            provider: keycloak-sso
            client-id: changeBackEnd
            client-secret: 947ed099-00d8-47ee-982f-9297701c2a1d
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9105/login/oauth2/code/keycloak    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


